<% ci_opts = " -r features --color --tags ~@on_demand --tags ~@wip --tags ~@unstable --tags ~@manual --tags ~@pending --format junit -o results/junit/ --format json -o results/cucumber.json --format Cucumber::Blinkbox::Formatter::Html -o results/features_report.html --format pretty"  %>

default: -p local_debug
local_debug: -r features --tags ~@wip environment=production debug=true --format pretty

ci-smoke-qa:          <%= ci_opts %> --tags @smoke environment=qa
ci-regression-qa:     <%= ci_opts %> --tags ~@smoke environment=qa

ci-smoke-production:  <%= ci_opts %> --tags @smoke --tags @production environment=production
