<% ci_opts = " -r features --color --tags ~@on_demand --tags ~@wip --tags ~@unstable --tags ~@manual --tags ~@pending --format junit -o results/junit/ --format Cucumber::Blinkbox::Formatter::Html -o features_report.html --format pretty"  %>

#default: -p local_debug
#local_debug: -r features --tags ~@wip environment=production debug=true --format pretty --color

ci-smoke-dev-debug:             <%= ci_opts %> --tags @smoke,@new_data environment=dev-debug BBB_ENV=DEVINT
ci-smoke-qa-debug:              <%= ci_opts %> --tags @smoke,@new_data environment=qa-debug BBB_ENV=QA
ci-smoke-production-debug:      <%= ci_opts %> --tags @smoke environment=production-debug BBB_ENV=PROD
ci-regression-dev-debug:        <%= ci_opts %> environment=dev-debug BBB_ENV=DEVINT
ci-regression-qa-debug:         <%= ci_opts %> environment=qa-debug BBB_ENV=QA
ci-regression-production-debug: <%= ci_opts %> --tags ~@new_data environment=production-debug BBB_ENV=PROD